[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_AZURE_CLIENT_ID = "d6aa1d05-2e2e-4c52-9c21-fe0f7d"
  VITE_AZURE_TENANT_ID = "common"
  VITE_REDIRECT_URI = "https://focus-friend.netlify.app"
  VITE_FIREBASE_API_KEY = "AIzaSyBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
  VITE_FIREBASE_AUTH_DOMAIN = "focus-friend.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID = "focus-friend"
  VITE_FIREBASE_STORAGE_BUCKET = "focus-friend.appspot.com"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "123456789012"
  VITE_FIREBASE_APP_ID = "1:123456789012:web:abcdef1234567890"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 