[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_AZURE_CLIENT_ID = "d6aa1d05-2e2e-4c52-9c21-fe0f7d"
  VITE_AZURE_TENANT_ID = "common"
  VITE_REDIRECT_URI = "https://focus-friend.netlify.app"
  VITE_FIREBASE_API_KEY = "AIzaSyCS1oLuwwzwUVInJ9l_yIt40_gryDpK2ss"
  VITE_FIREBASE_AUTH_DOMAIN = "focus-friend-536ad.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID = "focus-friend-536ad"
  VITE_FIREBASE_STORAGE_BUCKET = "focus-friend-536ad.firebasestorage.app"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "975734753164"
  VITE_FIREBASE_APP_ID = "1:975734753164:web:a60d3122a16b9c29dab8a9"
  VITE_FIREBASE_MEASUREMENT_ID = "G-JWXXYT2M3K"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 