[build]
  command = "rm -rf node_modules package-lock.json && npm install --legacy-peer-deps && npm run build"
  publish = "dist"

  [build.environment]
    NODE_VERSION = "18"
    VITE_AZURE_CLIENT_ID = ""
    VITE_AZURE_TENANT_ID = ""
    VITE_REDIRECT_URI = ""
    VITE_FIREBASE_API_KEY = ""
    VITE_FIREBASE_AUTH_DOMAIN = ""
    VITE_FIREBASE_PROJECT_ID = ""
    VITE_FIREBASE_STORAGE_BUCKET = ""
    VITE_FIREBASE_MESSAGING_SENDER_ID = ""
    VITE_FIREBASE_APP_ID = ""
    VITE_FIREBASE_MEASUREMENT_ID = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 